export const DEFAULT_DATA = {
  users: [
    { id: 1, username: 'admin', password: 'admin', name: 'Administrador', role: 'admin', active: true },
    { id: 2, username: 'cajero', password: 'cajero', name: 'Juan Pérez', role: 'cashier', active: true },
    { id: 3, username: 'cocina', password: 'cocina', name: 'María García', role: 'kitchen', active: true },
    { id: 4, username: 'mesero', password: 'mesero', name: 'Carlos López', role: 'waiter', active: true },
  ],
  productCategories: [
    { id: 'pizza', name: 'Pizzas', icon: '🍕', allowHalfAndHalf: true },
    { id: 'drink', name: 'Bebidas', icon: '🥤', allowHalfAndHalf: false },
    { id: 'extra', name: 'Extras', icon: '🍟', allowHalfAndHalf: false },
    { id: 'promo', name: 'Promociones', icon: '🎉', allowHalfAndHalf: false },
  ],
  products: [
    { id: 1, name: 'Pizza Margarita', category: 'pizza', price: 120, ingredients: [{ id: 1, qty: 0.2 }, { id: 2, qty: 0.15 }, { id: 3, qty: 0.1 }], active: true, icon: '🍕' },
    { id: 2, name: 'Pizza Pepperoni', category: 'pizza', price: 150, ingredients: [{ id: 1, qty: 0.2 }, { id: 2, qty: 0.15 }, { id: 4, qty: 0.1 }], active: true, icon: '🍕' },
    { id: 3, name: 'Pizza Hawaiana', category: 'pizza', price: 140, ingredients: [{ id: 1, qty: 0.2 }, { id: 2, qty: 0.15 }, { id: 5, qty: 0.08 }, { id: 6, qty: 0.05 }], active: true, icon: '🍍' },
    { id: 4, name: 'Pizza 4 Quesos', category: 'pizza', price: 160, ingredients: [{ id: 1, qty: 0.2 }, { id: 2, qty: 0.25 }], active: true, icon: '🧀' },
    { id: 5, name: 'Pizza Suprema', category: 'pizza', price: 180, ingredients: [{ id: 1, qty: 0.2 }, { id: 2, qty: 0.2 }, { id: 4, qty: 0.08 }, { id: 7, qty: 0.05 }, { id: 8, qty: 0.05 }], active: true, icon: '🍄' },
    { id: 6, name: 'Coca Cola 600ml', category: 'drink', price: 25, ingredients: [{ id: 9, qty: 1 }], active: true, icon: '🥤' },
    { id: 7, name: 'Sprite 600ml', category: 'drink', price: 25, ingredients: [{ id: 10, qty: 1 }], active: true, icon: '🥤' },
    { id: 8, name: 'Agua Natural 600ml', category: 'drink', price: 18, ingredients: [{ id: 11, qty: 1 }], active: true, icon: '💧' },
    { id: 9, name: 'Cerveza', category: 'drink', price: 35, ingredients: [{ id: 12, qty: 1 }], active: true, icon: '🍺' },
    { id: 10, name: 'Palitos de Ajo', category: 'extra', price: 45, ingredients: [{ id: 1, qty: 0.1 }, { id: 13, qty: 0.02 }], active: true, icon: '🥖' },
    { id: 11, name: 'Alitas BBQ (6 pzas)', category: 'extra', price: 85, ingredients: [{ id: 14, qty: 0.3 }], active: true, icon: '🍗' },
    { id: 12, name: 'Ensalada César', category: 'extra', price: 65, ingredients: [{ id: 15, qty: 0.15 }], active: true, icon: '🥗' },
    { id: 13, name: '2x1 Margarita', category: 'promo', price: 199, ingredients: [{ id: 1, qty: 0.4 }, { id: 2, qty: 0.3 }, { id: 3, qty: 0.2 }], active: true, icon: '🎉' },
    { id: 14, name: 'Combo Familiar', category: 'promo', price: 350, ingredients: [{ id: 1, qty: 0.4 }, { id: 2, qty: 0.3 }, { id: 4, qty: 0.15 }, { id: 9, qty: 2 }], active: true, icon: '👨‍👩‍👧‍👦' },
  ],
  inventory: [
    { id: 1, name: 'Masa para pizza', unit: 'kg', stock: 25, minStock: 5, cost: 30, supplier: 'Harinas del Norte', category: 'basicos' },
    { id: 2, name: 'Queso Mozzarella', unit: 'kg', stock: 15, minStock: 3, cost: 120, supplier: 'Lácteos Premium', category: 'basicos' },
    { id: 3, name: 'Salsa de Tomate', unit: 'lt', stock: 10, minStock: 2, cost: 45, supplier: 'Salsas Italianas', category: 'basicos' },
    { id: 4, name: 'Pepperoni', unit: 'kg', stock: 8, minStock: 2, cost: 180, supplier: 'Embutidos Express', category: 'carnes' },
    { id: 5, name: 'Jamón', unit: 'kg', stock: 6, minStock: 1.5, cost: 95, supplier: 'Embutidos Express', category: 'carnes' },
    { id: 6, name: 'Piña', unit: 'kg', stock: 4, minStock: 1, cost: 35, supplier: 'Frutas Frescas', category: 'verduras' },
    { id: 7, name: 'Champiñones', unit: 'kg', stock: 3, minStock: 1, cost: 85, supplier: 'Verduras del Campo', category: 'verduras' },
    { id: 8, name: 'Pimiento', unit: 'kg', stock: 2.5, minStock: 0.5, cost: 40, supplier: 'Verduras del Campo', category: 'verduras' },
    { id: 9, name: 'Coca Cola 600ml', unit: 'pza', stock: 48, minStock: 12, cost: 12, supplier: 'Distribuidora Refrescos', category: 'bebidas' },
    { id: 10, name: 'Sprite 600ml', unit: 'pza', stock: 36, minStock: 12, cost: 12, supplier: 'Distribuidora Refrescos', category: 'bebidas' },
    { id: 11, name: 'Agua Natural 600ml', unit: 'pza', stock: 60, minStock: 24, cost: 8, supplier: 'Distribuidora Refrescos', category: 'bebidas' },
    { id: 12, name: 'Cerveza', unit: 'pza', stock: 24, minStock: 12, cost: 18, supplier: 'Distribuidora Bebidas', category: 'bebidas' },
    { id: 13, name: 'Ajo', unit: 'kg', stock: 1, minStock: 0.3, cost: 60, supplier: 'Verduras del Campo', category: 'verduras' },
    { id: 14, name: 'Alitas de Pollo', unit: 'kg', stock: 5, minStock: 2, cost: 75, supplier: 'Carnes Selectas', category: 'carnes' },
    { id: 15, name: 'Lechuga Romana', unit: 'kg', stock: 3, minStock: 1, cost: 25, supplier: 'Verduras del Campo', category: 'verduras' },
  ],
  suppliers: [
    { id: 1, name: 'Harinas del Norte', contact: '555-0101', email: 'harinas@norte.com' },
    { id: 2, name: 'Lácteos Premium', contact: '555-0102', email: 'ventas@lacteospremium.com' },
    { id: 3, name: 'Salsas Italianas', contact: '555-0103', email: 'pedidos@salsasitalianas.com' },
    { id: 4, name: 'Embutidos Express', contact: '555-0104', email: 'ventas@embutidosexpress.com' },
    { id: 5, name: 'Verduras del Campo', contact: '555-0105', email: 'contacto@verdurasdelcampo.com' },
    { id: 6, name: 'Distribuidora Refrescos', contact: '555-0106', email: 'pedidos@distrefrescos.com' },
    { id: 7, name: 'Distribuidora Bebidas', contact: '555-0107', email: 'ventas@distbebidas.com' },
    { id: 8, name: 'Frutas Frescas', contact: '555-0108', email: 'ventas@frutasfrescas.com' },
    { id: 9, name: 'Carnes Selectas', contact: '555-0109', email: 'pedidos@carnesselectas.com' },
  ],
  tables: [
    { id: 1, name: 'Mesa 1', capacity: 4, status: 'free', xP: 15, yP: 20 },
    { id: 2, name: 'Mesa 2', capacity: 4, status: 'free', xP: 45, yP: 20 },
    { id: 3, name: 'Mesa 3', capacity: 6, status: 'free', xP: 75, yP: 20 },
    { id: 4, name: 'Mesa 4', capacity: 6, status: 'free', xP: 15, yP: 50 },
    { id: 5, name: 'Mesa 5', capacity: 2, status: 'free', xP: 45, yP: 50 },
    { id: 6, name: 'Mesa 6', capacity: 2, status: 'free', xP: 75, yP: 50 },
    { id: 7, name: 'Mesa 7', capacity: 8, status: 'free', xP: 25, yP: 75 },
    { id: 8, name: 'Mesa 8', capacity: 4, status: 'free', xP: 65, yP: 75 },
  ],
  orders: [],
  sales: [],
  cashRegister: { isOpen: false, openedBy: null, openedAt: null, initialAmount: 0, movements: [] },
  inventoryMovements: [],
  activityLog: [],
  notifications: [],
  kitchenReports: [],
  modifiers: [],
  expenses: [],
  settings: { systemMode: 'full', ownerWhatsApp: '' },
  inventoryCategories: [],
  franchiseBranches: ['sucursal_centro'],
}
